import { expect, test } from "@playwright/test";

test("salesforce fileupload",async({page})=>{
    await page.goto("https://login.salesforce.com/")
    await page.locator(`#username`).fill("udaya18udai318@agentforce.com")
    await page.locator(`#password`).fill("Sales@123")
    await page.locator(`#Login`).click()
    await page.waitForTimeout(2000)
    await page.locator(`//button[@title="App Launcher"]`).click()
    await page.locator(`//button[@aria-label="View All Applications"]`).click()
    const pageac= page.getByPlaceholder(`Search apps or items...`).fill('Accounts')
    // await pageac.fill('Accounts')
    // await pageac.press('Enter')
    await page.locator(`//mark[text()='Accounts']`).click()
    await page.locator(`//div[@title="New"]`).click()
    await page.locator(`(//div[@type="text"])[1]`).fill('karan')
    await page.getByRole(`combobox`, { name: `Rating` }).click()
    // //await page.selectOption(`.slds-combobox__input slds-input_faux fix-slds-input_faux slds-combobox__input-value`, { index: 1 })
    // await page.locator(`(//button[@role="combobox"])[1]`).click()
    await page.click(`text="Warm"`)
    await page.getByRole(`combobox`, {name: 'Type'}).click()
    await page.click(`text='Prospect'`)
    await page.getByRole(`combobox`,{name: "Industry"}).click()
    await page.click(`text="Banking"`)
    await page.getByRole(`combobox`,{name: "Ownership"}).click()
    await page.click(`text='Public'`)
    await page.locator(`//button[@name="SaveEdit"]`).click()
    await page.waitForSelector(`//span[contains(@class,'toastMessage')]`,{state: 'hidden'})
    const toastmesge = page.locator(`//span[contains(@class,'toastMessage')]`).innerText()
    console.log(toastmesge)
    await expect(toastmesge).toContain(`Account "karan" was created.`)
    const filecre = page.waitForEvent("filechooser")
    page.locator(`//div[@title="Upload Files"]`).click()
    const fileuplo = await filecre
    await page.waitForTimeout(2000)
    await fileuplo.setFiles(`Data/learningfileupload.txt`)
    await page.locator(`//span[@class=" label bBody"]`).click()

    const donemesage = page.locator(`//span[contains(@class,'toastMessage')]`).innerText()
    console.log(donemesage)
    await expect(donemesage).toContain("//1 file was added to the Account.")
    await page.waitForTimeout(2000)

})
